### ISSUE TITLE
Services should fail on startup if APPLICATION_CONFIG_PATH doesn't exist

### ISSUE THREAD

**Issue by rhyolight** [numenta/numenta-apps#33]
Currently I get a stacktrace that masks the source of the error, which is a missing `APPLICATION_CONFIG_PATH` environment variable. 

```
Traceback (most recent call last):
  File "start_listeners.py", line 3, in <module>
    from htmengine.runtime import metric_listener
  File "/Users/mtaylor/nta/numenta-apps/htmengine/htmengine/runtime/metric_listener.py", line 49, in <module>
    from htmengine.model_swapper.model_swapper_interface import (
  File "/Users/mtaylor/nta/numenta-apps/htmengine/htmengine/model_swapper/model_swapper_interface.py", line 551, in <module>
    class ModelSwapperInterface(object):
  File "/Users/mtaylor/nta/numenta-apps/htmengine/htmengine/model_swapper/model_swapper_interface.py", line 570, in ModelSwapperInterface
    _RESULTS_Q_ENV_VAR = ModelSwapperConfig()._getEnvVarOverrideName(
  File "/Users/mtaylor/nta/numenta-apps/htmengine/htmengine/model_swapper/__init__.py", line 42, in __init__
    os.environ.get("APPLICATION_CONFIG_PATH"))
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nta.utils-0.0.0-py2.7.egg/nta/utils/config.py", line 165, in __init__
    self.loadConfig()
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nta.utils-0.0.0-py2.7.egg/nta/utils/config.py", line 227, in loadConfig
    self._getConfigOverrideDir(),
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nta.utils-0.0.0-py2.7.egg/nta/utils/config.py", line 314, in _getConfigOverrideDir
    return os.path.join(self.baseConfigDir, self._CONFIG_OVERRIDE_DIR_NAME)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by oxtopus** [comment]
It does fail fast.  Are you suggesting that it should explicitly report some sort of user-friendly error?  Where should the error be displayed, and when should that be triggered?

It's in the README that ``APPLICATION_CONFIG_PATH`` is required to be in the environment _before_ any services are started.

**Comment by rhyolight** [comment]
I changed the name. I think services should fail on startup if the environment is wrong. Otherwise the failure isn't known until services start servicing. I can start up the metric listener service, for example, and it doesn't fail until I try to push it data.

**Comment by oxtopus** [comment]
I proposed a solution in #36, but only afterward realized something.  Grok prints a warning during `python setup.py init` (https://github.com/numenta/numenta-apps/blob/master/grok/pavement.py#L165-L175), and Taurus sets the `APPLICATION_CONFIG_PATH` envvar in supervisord.conf (https://github.com/numenta/numenta-apps/blob/master/taurus/conf/supervisord.conf#L16).  In both cases, the _application_ takes measures to mitigate issues related to the user not following explicit instructions.  But, if you're writing your own application from scratch, which I suspect you are, you likely won't have done the same unless you knew to in advance.

**Comment by rhyolight** [comment]
> But, if you're writing your own application from scratch, which I suspect you are, you likely won't have done the same unless you knew to in advance.

Exactly true.
