### ISSUE TITLE
The 'taurus' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by vitaly-krugl** [numenta/numenta-apps#682]
This was brought up by a user on the nupic-discussion list. The user was installing on Ubuntu (running in VirtualBox)

According to the readme “With taurus installed, and configuration updated, run taurus-create-db to initialize the database”. However, when I tried to run taurus-create-db, I faced the following error. Please advise if I missed some steps, or miss any configurations.

```
Using /usr/local/lib/python2.7/dist-packages/apipkg-1.4-py2.7.egg
Finished processing dependencies for taurus.engine==0.4.0
/home/meharu/numenta-apps
root@meharu-VirtualBox:/home/meharu/numenta-apps# export APPLICATION_CONFIG_PATH=/home/meharu/numenta-apps/taurus/conf-user/
root@meharu-VirtualBox:/home/meharu/numenta-apps# cd /usr/local/bin/
root@meharu-VirtualBox:/usr/local/bin# taurus-create-db
Traceback (most recent call last):
  File "/usr/local/bin/taurus-create-db", line 9, in <module>
    load_entry_point('taurus.engine', 'console_scripts', 'taurus-create-db')()
 File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 547, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2720, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2380, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2386, in resolve
  File "/home/meharu/numenta-apps/taurus/taurus/engine/__init__.py", line 12, in <module>
    distribution = get_distribution("taurus")
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 540, in get_distribution
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 420, in get_provider
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 941, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 828, in resolve
pkg_resources.DistributionNotFound: The 'taurus' distribution was not found and is required by the application
root@meharu-VirtualBox:/usr/local/bin#
```

**Comment by vitaly-krugl** [comment]
I was able to reproduce the problem that you¹re experiencing on Ubuntu 64bit running in VirtualBox, using Python 2.7.6. As a temporary work-around for the bug, users may try the following:

In taurus/taurus/engine/init.py, try changing the string parameter taurus to taurus.engine in the statement
distribution = get_distribution("taurus")
