### ISSUE TITLE
Cap'n Proto dependency not acquired during HTM Engine build

### ISSUE THREAD

**Issue by kevincoghlan** [numenta/numenta-apps#75]
I recently tried building HTM Engine, on a Fedora 22 server, with the 'python setup.py develop --user' command.

The build process detected that the Cap'n Proto dependency was missing, and attempted to obtain this dependency:

```
"*WARNING* no libcapnp detected. Will download and build it from source now. If you have C++ Cap'n Proto installed, it may be out of date or is not being detected. Downloading and building libcapnp may take a while."
```

Unfortunately, this failed to work, and the build was terminated.

I manually obtained a Cap'n Proto C++ 0.5.2 tarball from the Cap'n Proto website (Fedora doesn't have it in its repos), installed it, and then retried the HTM Engine build. This time it built successfully.

I thought I would bring this to your attention in case others encounter the same problem; perhaps there is something that can be rectified in the build process to avoid the error below. Alternatively, the requirement for installing Cap'n Proto prior to building HTM Engine could be documented.

Full error text:

```
... <earlier installation text> ...

Searching for pycapnp==0.5.5
Reading https://pypi.python.org/simple/pycapnp/
Best match: pycapnp 0.5.5
Downloading https://pypi.python.org/packages/source/p/pycapnp/pycapnp-0.5.5.tar.gz#md5=71570126bbec8b38f992b1e8feebaeab
Processing pycapnp-0.5.5.tar.gz
Writing /tmp/easy_install-ccVTLA/pycapnp-0.5.5/setup.cfg
Running pycapnp-0.5.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ccVTLA/pycapnp-0.5.5/egg-dist-tmp-2k3MUJ
/tmp/easy_install-ccVTLA/pycapnp-0.5.5/temp/timer_createonzcn0.c:1:1: warning: return type defaults to ‘int’ [-Wimplicit-int]
 main (int argc, char **argv) {
 ^
/tmp/easy_install-ccVTLA/pycapnp-0.5.5/temp/timer_createonzcn0.c: In function ‘main’:
/tmp/easy_install-ccVTLA/pycapnp-0.5.5/temp/timer_createonzcn0.c:2:5: warning: implicit declaration of function ‘timer_create’ [-Wimplicit-function-declaration]
     timer_create();
     ^
/tmp/easy_install-ccVTLA/pycapnp-0.5.5/temp/tmp1Smrqi/tmp/easy_install-ccVTLA/pycapnp-0.5.5/temp/timer_createonzcn0.o: In function `main':
timer_createonzcn0.c:(.text+0x15): undefined reference to `timer_create'
collect2: error: ld returned 1 exit status
/tmp/easy_install-ccVTLA/pycapnp-0.5.5/temp/tmp1Smrqi/vers.cpp:4:26: fatal error: capnp/common.h: No such file or directory
compilation terminated.
*WARNING* no libcapnp detected. Will download and build it from source now. If you have C++ Cap'n Proto installed, it may be out of date or is not being detected. Downloading and building libcapnp may take a while.
fetching https://capnproto.org/capnproto-c++-0.5.1.2.tar.gz into /tmp/easy_install-ccVTLA/pycapnp-0.5.5/bundled
src/capnp/schema.c++: In member function 'bool capnp::InterfaceSchema::extends(capnp::InterfaceSchema, capnp::uint&) const':
src/capnp/schema.c++:602:12: error: converting to 'bool' from 'std::nullptr_t' requires direct-initialization [-fpermissive]
     return nullptr;
            ^
make: *** [src/capnp/schema.lo] Error 1
make: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    dependency_links = depLinks,
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/develop.py", line 32, in run
    self.install_for_development()
  File "/usr/lib/python2.7/site-packages/setuptools/command/develop.py", line 132, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 709, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 830, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1075, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1087, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 629, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 659, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 842, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1070, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1056, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 240, in run_setup
    raise
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 164, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 139, in resume
    compat.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 237, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 267, in run
    return func()
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 236, in runner
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-ccVTLA/pycapnp-0.5.5/setup.py", line 168, in <module>

  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 160, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 146, in call_command
    self.run_command(cmdname)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install_lib.py", line 10, in run
    self.build()
  File "/usr/lib64/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-ccVTLA/pycapnp-0.5.5/setup.py", line 112, in run

  File "/tmp/easy_install-ccVTLA/pycapnp-0.5.5/buildutils/build.py", line 26, in build_libcapnp
RuntimeError: Make failed
```

**Comment by jcasner** [comment]
@kevincoghlan thanks for the heads up!  This is the first I've heard of this particular issue, so we'll have to do some investigations.  We're still in the process of implementing Capn Proto in NuPIC, so this may be something that @scottpurdy needs to be aware of as he continues to replace our old serialization tools and formats with Capn Proto.

As we try to reproduce and fix this, it would be helpful to know which versions of python, gcc, and make you are using.  Thanks!

**Comment by scottpurdy** [comment]
The pycapnp Python library always checks for a local install first but then falls back to downloading and building capnp. So you will see those errors initially but it then goes and fetches the appropriate source version of capnp. It looks like the actual issue was in building capnp. Please check out the pycapnp documentation to see if the issue is outlined there:
https://github.com/jparyani/pycapnp

**Comment by scottpurdy** [comment]
NuPIC doesn't require anything special when installing pycapnp so if the problem persists then I recommend filing an issue on the pycapnp GH repo.

**Comment by kevincoghlan** [comment]
Thanks for the clarification @scottpurdy ; as mentioned, I have installed Cap'n Proto manually, so HTM Engine is building fine for me now. I just thought I would flag the hitch for you guys in case anyone else encounters it while trying to build HTM Engine.

No probs @jcasner, happy to be of any help. In case you are still interested in those versions, here they are:

Python 2.7.10
gcc 5.1.1
Make 4.0
